apiVersion: v1
kind: Service
metadata:
  name: demo-cncf-1
  namespace: demo-apps
  labels:
    app: demo-cncf-1
    backstage.io/kubernetes-id: demo-cncf-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: demo-cncf-1
